# Generated by Django 3.2.12 on 2024-07-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq',
            new_name='faq_list',
        ),
    ]
