# Generated by Django 5.0.7 on 2024-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_subscription_subscriptionfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='highlight_status',
            field=models.BooleanField(default=False),
        ),
    ]
