# Generated by Django 5.0.7 on 2024-07-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_subscription_highlight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='subscriptionfeature',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='subscription',
            field=models.ManyToManyField(to='base.subscription'),
        ),
    ]
