# Generated by Django 5.0.7 on 2024-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_subscription_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_num',
            field=models.IntegerField(null=True),
        ),
    ]
