# Generated by Django 5.0.7 on 2024-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_subscription_max_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='availiable',
            field=models.IntegerField(null=True),
        ),
    ]
