# Generated by Django 5.0.7 on 2024-08-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_subs_subscriber_user_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='sub_feature',
        ),
        migrations.AddField(
            model_name='sub',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subscription'),
        ),
    ]
