# Generated by Django 5.0.7 on 2024-08-04 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_sub_sub_feature_sub_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub',
            new_name='SubscribedUsers',
        ),
    ]
